# Generated by Django 4.0.5 on 2022-06-11 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0002_remove_studenteconomy_name_studenteconomy_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenteconomy',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studenteconomy',
            name='last_name',
        ),
        migrations.AddField(
            model_name='studenteconomy',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sp.student'),
        ),
    ]
