# Generated by Django 4.0.5 on 2022-06-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0003_remove_studenteconomy_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economy',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='studenteconomy',
            name='student',
        ),
        migrations.AddField(
            model_name='studenteconomy',
            name='economy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sp.economy'),
        ),
        migrations.AlterField(
            model_name='economy',
            name='student',
            field=models.ManyToManyField(to='sp.student'),
        ),
    ]
