# Generated by Django 4.0.5 on 2022-06-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0004_remove_economy_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteconomy',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studenteconomy',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
