# Generated by Django 4.0.5 on 2022-06-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0007_remove_studenteconomy_economy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economy',
            name='student',
            field=models.ManyToManyField(to='sp.studenteconomy'),
        ),
    ]
