# Generated by Django 4.0.5 on 2022-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0008_alter_economy_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteconomy',
            name='teacher',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
