# Generated by Django 4.0.5 on 2022-06-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0016_alter_studenteconomy_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenteconomy',
            old_name='active',
            new_name='status',
        ),
    ]
