# Generated by Django 4.0.5 on 2022-06-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0017_rename_active_studenteconomy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteconomy',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
