# Generated by Django 4.0.5 on 2022-06-13 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0018_alter_studenteconomy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='four_pin',
        ),
    ]
