# Generated by Django 4.0.5 on 2022-06-13 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0019_remove_teacher_four_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, null=True)),
                ('school_logo', models.ImageField(blank=True, default='default_logo.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sp.school'),
        ),
    ]
