# Generated by Django 4.0.5 on 2022-06-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0020_school_teacher_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_logo',
            field=models.ImageField(blank=True, default='default_logo.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
