# Generated by Django 4.0.5 on 2022-06-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0022_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sp.teacher'),
        ),
    ]
