# Generated by Django 4.0.5 on 2022-06-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0024_alter_job_student_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='student_assigned',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
