# Generated by Django 4.0.5 on 2022-06-13 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0030_alter_job_student_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='student_assigned',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sp.student'),
        ),
    ]
